---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumearchiver-operator
rules:
  - apiGroups:
      - volumearchiver.rcluff.com
    resources:
      - backupjobs
      - restorejobs
    verbs:
      - get
      - watch
      - list
      - patch

  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - watch
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
      - patch
      - get
      - watch
      - list
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - patch
      - get
      - watch
      - list
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
      - jobs/status
    verbs:
      - create
      - patch
      - get
      - watch
      - list
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volumearchiver-operator
subjects:
  - kind: ServiceAccount
    name: volumearchiver-operator
    namespace: volumearchiver
roleRef:
  kind: ClusterRole
  name: volumearchiver-operator
  apiGroup: rbac.authorization.k8s.io
