---
apiVersion: v1
kind: Service
metadata:
  name: volumearchiver-config
  namespace: volumearchiver

spec:
  ports:
    - name: debug
      protocol: TCP
      port: 5678
  type: LoadBalancer
  loadBalancerIP: 192.168.0.38
  selector:
    app: volumearchiver
