apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumearchiver-operator
  namespace: volumearchiver

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: volumearchiver-operator
  labels:
    app: volumearchiver
  namespace: volumearchiver

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: volumearchiver
  template:
    metadata:
      labels:
        app: volumearchiver
    spec:
      serviceAccount: volumearchiver-operator
      containers:
        - name: volumearchiver-operator
          image: registry.it.rcluff.com/va-operator:0.1
          imagePullPolicy: Always
          ports:
            - name: debug
              containerPort: 5678
              protocol: TCP
