# Start from ubuntu:22.04 base image
FROM ubuntu:22.04

# Install python and other dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

WORKDIR /app
COPY ./requirements.txt .

RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY ./templates ./templates
COPY ./main.py .

# This is what runs when the container is started
CMD ["kopf", "run", "main.py", "--verbose", "-A"]
