---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-sh
  namespace: homeassistant
data:
  restore.sh: |
    #!/bin/bash
    for i in /mnt/source/* ; do
      if [ -d "$i" ]; then
        tar -xvzf "/mnt/destination/$(basename $i).tar.gz"
      fi
    done

      

---
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
  namespace: homeassistant
spec:
  template:
    spec:
      containers:
        - name: restore
          image: ubuntu:20.04
          command:
            - "job/restore.sh"
          tty: true
          volumeMounts:
            - name: restore-sh
              mountPath: /job
            - name: backup
              mountPath: /mnt/destination
            - name: homeassistant-config
              mountPath: /mnt/source/homeassistant-config
      volumes:
        - name: restore-sh
          configMap:
            name: restore-sh
            defaultMode: 0777
        - name: backup
          nfs:
            server: nas01.rcluff.com
            path: /mnt/storage/backup
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config
      restartPolicy: Never
  backoffLimit: 1