FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

WORKDIR /app
COPY ./requirements.txt .

RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY ./image_generator.yml .
COPY ./main.py .
COPY ./settings.py .
COPY ./status.py .

# This is what runs when the container is started
CMD ["python3", "main.py"]
